name: "@ALL"

on:
  workflow_dispatch:
    inputs:
      mpi4py-git:
        description: 'mpi4py git'
        default:  mpi4py/mpi4py
        required: true
        type: string
      mpi4py-ref:
        description: 'mpi4py ref'
        default:  master
        required: true
        type: string
  push:
    branches:
      - gh-workflow/@ALL

jobs:

  mpich:
    uses: ./.github/workflows/mpich.yml
    with:
      mpi4py-git: ${{ github.event.inputs.mpi4py-git }}
      mpi4py-ref: ${{ github.event.inputs.mpi4py-ref }}

  openmpi:
    uses: ./.github/workflows/openmpi.yml
    with:
      mpi4py-git: ${{ github.event.inputs.mpi4py-git }}
      mpi4py-ref: ${{ github.event.inputs.mpi4py-ref }}

  intelmpi:
    uses: ./.github/workflows/intelmpi.yml
    with:
      mpi4py-git: ${{ github.event.inputs.mpi4py-git }}
      mpi4py-ref: ${{ github.event.inputs.mpi4py-ref }}

  mvapich:
    uses: ./.github/workflows/mvapich.yml
    with:
      mpi4py-git: ${{ github.event.inputs.mpi4py-git }}
      mpi4py-ref: ${{ github.event.inputs.mpi4py-ref }}
